// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlWodmnZPBp7QDlZVEQ5o6KqKqrjPUi1k',
    appId: '1:689078917281:web:64517659c96ddbd80638e0',
    messagingSenderId: '689078917281',
    projectId: 'job-getter-3aa8b',
    authDomain: 'job-getter-3aa8b.firebaseapp.com',
    storageBucket: 'job-getter-3aa8b.firebasestorage.app',
    measurementId: 'G-8HWXBTERGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY8WECx-YmHrmKLWC3c0CtWKYq8jUnfTE',
    appId: '1:689078917281:android:bb2bec634258e0bc0638e0',
    messagingSenderId: '689078917281',
    projectId: 'job-getter-3aa8b',
    storageBucket: 'job-getter-3aa8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7qRSsOFspxhTRbE7uti-cAXW0gzDGQY',
    appId: '1:689078917281:ios:94938d224749582b0638e0',
    messagingSenderId: '689078917281',
    projectId: 'job-getter-3aa8b',
    storageBucket: 'job-getter-3aa8b.firebasestorage.app',
    iosBundleId: 'com.example.jobGetterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq7qRSsOFspxhTRbE7uti-cAXW0gzDGQY',
    appId: '1:689078917281:ios:94938d224749582b0638e0',
    messagingSenderId: '689078917281',
    projectId: 'job-getter-3aa8b',
    storageBucket: 'job-getter-3aa8b.firebasestorage.app',
    iosBundleId: 'com.example.jobGetterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlWodmnZPBp7QDlZVEQ5o6KqKqrjPUi1k',
    appId: '1:689078917281:web:166698dd51d1ddca0638e0',
    messagingSenderId: '689078917281',
    projectId: 'job-getter-3aa8b',
    authDomain: 'job-getter-3aa8b.firebaseapp.com',
    storageBucket: 'job-getter-3aa8b.firebasestorage.app',
    measurementId: 'G-WXRM2YMM5G',
  );
}
